### ISSUE TITLE
Why "treehouse"?

### ISSUE THREAD

**Issue by iainbeeston** [markevans/treehouse#1]
I hate to say it, but treehouse is a pain to find on google (most results are for https://github.com/treehouse). Did you ever consider another name? What's the rationale behind "treehouse"?

**Comment by markevans** [comment]
Lol I don't mind that it doesn't come up on google as it's not mature enough yet and hasn't been publicised. I like the name coz it rings well. The rational comes from the fact that it uses cursors to navigate a big tree. The cursors are like windows into the data, or sort of like lil'  treehouses at different points on the tree

**Comment by iainbeeston** [comment]
Nice. I'll close this then
